# permissions for end users to view certchecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certcheck-viewer-role
rules:
- apiGroups:
  - sre.amsy810.dev
  resources:
  - certchecks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sre.amsy810.dev
  resources:
  - certchecks/status
  verbs:
  - get
